// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQLZiHhcA7dYnzwiw3KZsIvDJchJQXA8c',
    appId: '1:571408789555:web:194147e638e7232597b346',
    messagingSenderId: '571408789555',
    projectId: 'fleetpoint-d5c6d',
    authDomain: 'fleetpoint-d5c6d.firebaseapp.com',
    storageBucket: 'fleetpoint-d5c6d.firebasestorage.app',
    measurementId: 'G-ZSVXXLGFNE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGQR_9SFcz207aLSADO8V6DHULGGXlXcc',
    appId: '1:571408789555:android:c03c27eb8f260c3797b346',
    messagingSenderId: '571408789555',
    projectId: 'fleetpoint-d5c6d',
    storageBucket: 'fleetpoint-d5c6d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI4v2piT8n6oi-aQGWLNWExz21APmpTr4',
    appId: '1:571408789555:ios:8430a46be31f271297b346',
    messagingSenderId: '571408789555',
    projectId: 'fleetpoint-d5c6d',
    storageBucket: 'fleetpoint-d5c6d.firebasestorage.app',
    iosBundleId: 'com.example.skyload',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI4v2piT8n6oi-aQGWLNWExz21APmpTr4',
    appId: '1:571408789555:ios:8430a46be31f271297b346',
    messagingSenderId: '571408789555',
    projectId: 'fleetpoint-d5c6d',
    storageBucket: 'fleetpoint-d5c6d.firebasestorage.app',
    iosBundleId: 'com.example.skyload',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQLZiHhcA7dYnzwiw3KZsIvDJchJQXA8c',
    appId: '1:571408789555:web:f45210c5a1c6430a97b346',
    messagingSenderId: '571408789555',
    projectId: 'fleetpoint-d5c6d',
    authDomain: 'fleetpoint-d5c6d.firebaseapp.com',
    storageBucket: 'fleetpoint-d5c6d.firebasestorage.app',
    measurementId: 'G-HTFXSQXBRQ',
  );
}
